trigger:
  - pipeline
pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: GitVersion@5
    displayName: 'GitVersion'
    inputs:
      updateAssemblyInfo: true
      preferBundledVersion: false

  - script: echo %Action%%BuildVersion%
    displayName: 'Set build version'
    env:
      Action: '##vso[build.updatebuildnumber]'
      BuildVersion: $(GitVersion.SemVer)

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/Clave.MementoMori.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '**/Clave.MementoMori.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test $(buildConfiguration)'
    inputs:
      command: 'test'
      projects: '**/*Tests/Clave.MementoMori.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack $(buildConfiguration)'
    inputs:
      command: 'pack'
      projects: '**/Clave.MementoMori.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
      nobuild: true

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'Nuget'
  - task: NuGetCommand@2
    inputs:
      command: push
      nuGetFeedType: external
      versioningScheme: byEnvVar
      versionEnvVar: '$(GitVersion.SemVer)'